map = {"11": "velocity",
       "36": "Seat driver OC",
       "37": "Seat co-driver OC",
       "43": "ABS OC",
       "47": "ASR OC",
       "101": "ESP OC",
       "156": "Charisma gearbox OC",
       "175": "T_outside",
       "192": "Fuel status",
       "280": "Charisma engine OC",
       "281": "Engine speed",
       "282": "Break OC",
       "283": "Gas pedal position[%][0…100]",
       "287": "Kickdown	OC",
       "326": "Precipitation OC",
       "337": "Vehicle weight OC",
       "452": "Slope OC",
       "646": "Co-driver OC",
       "962": "Street category OC",
       "1158": "Acceleration x",
       "1159": "Acceleration y",
       "1160": "Acceleration z",
       "2804": "ESP emergency breake OC",
       "2843": "ACC distance (index) OC",
       "3377": "ACC distance warning",
       "4133": "Last GPS Sync OC",
       "4229": "Torque",
       "4483": "Driver breakes is equal",
       "4487": "Precipitation OC"}
